export const GET_DATA_START = "GET_DATA_START";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_ERROR";

export const GET_SWIPER_DATA_START = "GET_SWIPER_DATA_START";
export const GET_SWIPER_DATA_SUCCESS = "GET_SWIPER_DATA_SUCCESS";
export const GET_SWIPER_DATA_ERROR = "GET_SWIPER_DATA_ERROR";

export const GET_SWIPER_DATA1_START = "GET_SWIPER_DATA1_START";
export const GET_SWIPER_DATA1_SUCCESS = "GET_SWIPER_DATA1_SUCCESS";
export const GET_SWIPER_DATA1_ERROR = "GET_SWIPER_DATA1_ERROR";